CREATE TABLE USERS (
	ID        INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT user_pk PRIMARY KEY,
	NOM       Varchar(30) NOT NULL ,
	PRENOM    Varchar(30) NOT NULL ,
	LOGIN     Varchar(30) NOT NULL ,
	PASSWORD  Varchar(30) NOT NULL
);

CREATE TABLE TYPE_PIECE(
	ID  	Integer NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT type_piece_pk PRIMARY KEY,
	NOM 	Varchar(30)  NOT NULL
);

CREATE TABLE PIECE (
	ID      Integer NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT piece_pk PRIMARY KEY,
	NOM     Varchar(30) NOT NULL ,
	TYPE_PIECE_ID    Integer,
	FOREIGN KEY (TYPE_PIECE_ID) REFERENCES TYPE_PIECE(ID)
);

CREATE TABLE TYPE_EQUIPEMENT(
	ID  	Integer NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT type_equipement_pk PRIMARY KEY,
	NOM 	Varchar(30)  NOT NULL
);

CREATE TABLE EQUIPEMENT (
	ID          Integer NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT equipement_pk PRIMARY KEY,
	NOM         Varchar (30),
	DESCRIPTION Varchar (50),
	ETAT        Boolean ,
	RELAY       Varchar (30),
	PIECE_ID    Integer,
	TYPE_ID     Integer,
	FOREIGN KEY (PIECE_ID) REFERENCES PIECE(ID),
	FOREIGN KEY (TYPE_ID) REFERENCES TYPE_EQUIPEMENT(ID)
);

INSERT INTO USERS (NOM, PRENOM, LOGIN, PASSWORD) VALUES('nomTest', 'prenomTest', 'root', 'root');

INSERT INTO TYPE_PIECE (NOM) VALUES('Salon');
INSERT INTO TYPE_PIECE (NOM) VALUES('Cuisine');
INSERT INTO TYPE_PIECE (NOM) VALUES('Chambre');
INSERT INTO TYPE_PIECE (NOM) VALUES('Cours');
INSERT INTO TYPE_PIECE (NOM) VALUES('Garrage');
INSERT INTO TYPE_PIECE (NOM) VALUES('Autre');

INSERT INTO TYPE_EQUIPEMENT (NOM) VALUES('Lamps');
INSERT INTO TYPE_EQUIPEMENT (NOM) VALUES('Porte');

INSERT INTO PIECE (NOM, TYPE_PIECE_ID) VALUES('Salon', 1);
INSERT INTO PIECE (NOM, TYPE_PIECE_ID) VALUES('Cuisine', 2);
INSERT INTO PIECE (NOM, TYPE_PIECE_ID) VALUES('Chambre des parents', 3);
INSERT INTO PIECE (NOM, TYPE_PIECE_ID) VALUES('Chambre enfant', 3);

INSERT INTO EQUIPEMENT (NOM, DESCRIPTION, ETAT, RELAY, PIECE_ID, TYPE_ID) VALUES('Lamp 1', 'Lamp principale', false, '1', 1, 1);

